// Generated by https://quicktype.io

export interface GetRatesRes {
  "price-quotes": PriceQuotes;
}

interface PriceQuotes {
  "price-quote": PriceQuote[];
}

interface PriceQuote {
  "service-code":     string;
  "service-link":     ServiceLink;
  "service-name":     string;
  "price-details":    PriceDetails;
  "weight-details":   string;
  "service-standard": ServiceStandard;
}

interface PriceDetails {
  base:        number;
  taxes:       Taxes;
  due:         number;
  options:     Options;
  adjustments: Adjustments;
}

interface Adjustments {
  adjustment: Adjustment[];
}

interface Adjustment {
  "adjustment-code": string;
  "adjustment-name": string;
  "adjustment-cost": number;
  qualifier?:        AdjustmentQualifier;
}

interface AdjustmentQualifier {
  percent: number;
}

interface Options {
  option: Option;
}

interface Option {
  "option-code":  string;
  "option-name":  string;
  "option-price": number;
  qualifier?:     OptionQualifier;
}

interface OptionQualifier {
  included: boolean;
}

interface Taxes {
  gst: number;
  pst: number;
  hst: Hst;
}

interface Hst {
  "#text":     number; // value of the tax on this shipping
  "@_percent": string; // percentage representation
}

interface ServiceLink {
  "@_rel":        string;
  "@_href":       string;
  "@_media-type": string;
}

interface ServiceStandard {
  "am-delivery":            boolean;
  "guaranteed-delivery":    boolean;
  "expected-transit-time":  number;
  "expected-delivery-date": string;
}
