export const DOMAIN = process.env.NODE_ENV === "development"
	? "http://localhost:3000"
	: process.env.VERCEL === "true"
		? "https://jhy-electrical.vercel.app"
		: "https://jhyeletrical.ca"
export const PAYPALDOMAIN = process.env.NODE_ENV === "development" ? "https://api-m.sandbox.paypal.com" : "https://api-m.paypal.com"